name: Translate All Locales (Incremental)

on:
  push:
    branches:
      - master # Triggers on push to the 'master' branch
    paths:
      - 'src/global.yaml' # Triggers only if 'src/global.yaml' changes

jobs:
  translate-all-locales: # Renamed job for clarity
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository with history
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Fetch the current commit and its immediate parent for comparison

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install js-yaml @google/genai

      - name: Run Node.js script to translate ONLY changed YAML strings for all locales
        run: node .github/scripts/copy_yaml.js # Your script file name
        env:
          SOURCE_YAML_PATH: src/global.yaml
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GITHUB_SHA_BEFORE: ${{ github.event.before }}

      - name: Create Pull Request for all locale changes
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_FOR_PR }}
          commit-message: "feat: Auto-translate updated strings for all locales" # General commit message
          branch: feature/auto-translate # Fixed, long-lived branch name
          delete-branch: false # Keeps the branch for continuous updates
          title: "🤖 Auto-translate: Update All Locale Localizations" # General PR title
          body: |
            This Pull Request automatically updates `generated/<locale>/global.yaml` files with translations
            based on **only the changed strings** detected in `src/global.yaml`.

            Locales updated: es-es, fr-fr, jp-jp, ko-kr, ar-sa
            Triggered by commit: ${{ github.sha }}
            By: @${{ github.actor }}
            
            Please review and merge if translations are correct.
          labels: automated, localization, feature, multi-locale
          # --- IMPORTANT CHANGE HERE: Use a wildcard for multiple files ---
          add-paths: 'generated/**/*.yaml'
          # -----------------------------------------------------------------

      - name: Check Pull Request Output
        if: steps.cpr.outputs.pull-request-number
        run: |
          echo "Pull Request #${{ steps.cpr.outputs.pull-request-number }} created/updated."
          echo "URL: ${{ steps.cpr.outputs.pull-request-url }}"
