name: Translate Global YAML to French

on:
  push:
    branches:
      - master
    paths:
      - "src/global.yaml"

jobs:
  translate-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        # Removed @google-cloud/translate here
        run: npm install js-yaml @google/genai

      - name: Run Node.js script to translate YAML
        run: node .github/scripts/copy_yaml.js
        env:
          SOURCE_YAML_PATH: src/global.yaml
          TARGET_YAML_PATH: generated/global.yaml
          # --- Only GEMINI_API_KEY is needed now ---
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # ------------------------------------------

      - name: Commit and Push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add generated/global.yaml
          git commit -m "feat: Auto-translate generated/global.yaml to French [skip ci]" || echo "No actual changes to commit, proceeding."
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
