name: Translate Changed Global YAML to French (Incremental)

on:
  push:
    branches:
      - master # Triggers on push to the 'master' branch
    paths:
      - 'src/global.yaml' # Triggers only if 'src/global.yaml' changes

jobs:
  translate-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository with history
        uses: actions/checkout@v4
        with:
          # Fetch the current commit and its immediate parent for comparison
          # fetch-depth: 2 is usually enough to get the previous commit.
          # fetch-depth: 0 would get full history, but is slower.
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install js-yaml @google/genai

      - name: Run Node.js script to translate ONLY changed YAML strings
        run: node .github/scripts/copy_yaml.js # Your script file name
        env:
          SOURCE_YAML_PATH: src/global.yaml
          TARGET_YAML_PATH: generated/global.yaml
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # Pass the SHA of the commit BEFORE the current push
          # This is crucial for `git show` to get the previous version of the file
          GITHUB_SHA_BEFORE: ${{ github.event.before }}

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT_FOR_PRS }}
          commit-message: "feat: Auto-translate updated strings in generated/global.yaml" # Updated commit message
          branch: auto-translate/french-localization # Using a fixed branch name for continuous updates to the same PR
          delete-branch: true
          title: "🤖 Auto-translate: Update French Localization"
          body: |
            This Pull Request automatically updates `generated/global.yaml` with French translations
            based on **only the changed strings** detected in `src/global.yaml`.

            Triggered by commit: ${{ github.sha }}
            By: @${{ github.actor }}
            
            Please review and merge if translations are correct.
          labels: automated, localization, feature
          add-paths: 'generated/global.yaml'

      - name: Check Pull Request Output
        if: steps.cpr.outputs.pull-request-number
        run: |
          echo "Pull Request #${{ steps.cpr.outputs.pull-request-number }} created/updated."
          echo "URL: ${{ steps.cpr.outputs.pull-request-url }}"
